packages:
  - agent-framework
  - agentic-search
  - agentic-search/packages/*

onlyBuiltDependencies:
  - esbuild
  - onnxruntime-node
  - protobufjs
  - sharp
  - tree-sitter
  - tree-sitter-javascript
  - tree-sitter-typescript
